---
name: Checks
on:
    - push
    - workflow_dispatch
jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        env:
            SKIP_ENV_VALIDATION: true
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: npm
            - run: npm install
            - run: npm run lint
    tsc:
        name: Tsc
        runs-on: ubuntu-latest
        env:
            SKIP_ENV_VALIDATION: true
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: npm
            - run: npm install
            - run: npm run tsc
    sonar:
        name: Sonar scan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              with:
                  args: |
                      -Dsonar.organization=kaje94_menufic -Dsonar.projectKey=my-kajendran
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
